GET http://localhost:5206

###
GET http://localhost:5206/games

###
GET http://localhost:5206/games/3

###
POST  http://localhost:5206/games
Content-Type: application/json

{

  "genre": "Adventuredd",
  "price": 49.99,
  "releaseDate": "2023-09-15"
}

###
PUT  http://localhost:5206/games/5
Content-Type: application/json

{
  "name": "Game 2 edited ss",
  "genre": "Adventure",
  "price": 49.99,
  "releaseDate": "2023-09-15"
}

###
DELETE  http://localhost:5206/games/2